### ISSUE TITLE
project-check-in-1: GITHUB_ISSUE_URL

### ISSUE THREAD

**Issue by mansivashisth** [mansivashisth/ATLAS-iOS-Fall-22#1]
### **Screen shots** 

<img width="983" alt="Screen Shot 2022-10-10 at 8 15 34 AM" src="https://user-images.githubusercontent.com/31610977/196232109-0aa5ff88-947c-4766-be46-7a49f4264b2a.png">
<img width="983" alt="Screen Shot 2022-10-10 at 8 16 01 AM" src="https://user-images.githubusercontent.com/31610977/196232132-4f3509dd-9844-41a5-a59f-3bb440d902a1.png">

### ** Task List**
- [ ]  Add list feature 
- [ ]  Add element addition and deletion 
if have time 
- [ ]  Add time and alarm for the tasks in To Do List (if so name the app Bug Me)

### **Learning**
The basics of the language are the same as many other the only major difference is the syntax. Getting used to a new syntax takes time and lots of google search. I have not developed any app in the past few years so it is a good experience to create something new using Swift. I have so far created a navigation screen. 
The most difficult task so far had been deciding what app to create and how I want it to look. 
I have made quite a few edits and changes starting from a sketch app where you could write text and game app ideas to coming to a To Do List app. My future goal is to add alarm feature to it if I have the time.

**Comment by zef** [comment]
Hey Mansi! Glad to see that you have a good idea for what you want to work on!

Could you make sure your config file is updated to match the [repo requirements](https://zef.github.io/ATLAS-iOS/repo_requirements.html), and put your project on GitHub, and add the name to your `repo_names` field? Let me know if you have any questions about that.

In the screenshots I see that you are working on the todo list. Are you following any specific tutorials or anything like that?

It seems that you are using `UIKit` and `Storyboards`, which is definitely a valid way of writing iOS apps, but we have not been talking about that in class since we are focusing on `SwiftUI` — the newer framework for UI development on iOS. Hopefully that hasn't been too confusing!

Let me know if you'd like to discuss any of those things specifically and see what you'd like to do going forward. Without looking at your project I don't know how much time you have already put into that app.

Thanks!

**Comment by mansivashisth** [comment]
Hey Zef,

I have updated the config file. I I was initially using older tutorial links on youtube to work with so they used UIKit and Storyboards and I Worked with them. Recently i found some issues working with it so i am now updating my app and using SwiftUI and will be able to upload the basic functioning app with error handling by end of the week.
below are the links i am using to study. My app will be different from that is in the link but i am using them for reference for how models and lists work. Let me know if you have any better suggestions
https://developer.apple.com/tutorials/swiftui/building-lists-and-navigation
https://mdcode2021.medium.com/modern-todo-app-in-swiftui-with-mvvm-ff8248b137d3

Thanks

**Comment by zef** [comment]
Thank you Mansi, sorry for my slow response here.

Those resources look good. Just try to make sure you are getting an understanding by doing things a little bit on your own and not just copying the tutorials exactly — I find that to be a better way of learning.

One more followup on your repo name issue:

https://github.com/mansivashisth/ATLAS-iOS-Fall-22/blob/40f4eb1f8b18d76f7aae6e0f22977dbcef0f378c/config.yml#L4
The value here should not contain any spaces, because it should be part of the path in the GitHub repo for your project. In the case of this "class repo", the value is `ATLAS-iOS-Fall-22`. I don't see a public repo for your project. Do you have it pushed to GitHub yet? If so, it may be setup as a private repo.

You can leave it as a private repo as long as you add me as a "collaborator", otherwise you can make it public so I can access it.

Thank you!

**Comment by mansivashisth** [comment]
Hi Zef please check in main branch -> Project folder for the code. Sorry for the delay due to laptop crash.

Thanks!
